### PR TITLE
L10 Location

### PR DESCRIPTION
**Pull request by Nianmi**
This change details the location of L10. While its location is depicted in the RAK4630 module schematic, no documentation exists on how to remove it. After reverse engineering the RAK4630 for a couple of hours yesterday, I located L10. This reduced the power consumption of the RAK4630 from approximately 300µA to 25µA.

Furthermore, I reviewed all discussions on the forum, and no mention of L10's location was found.

### CODE REVIEW

**Comment by carlrakwireless** [comment]
Hi @Nianmi ,

Thank you for your contribution on our documentation. We appreciate your help for the RAK user community.

We understand what you mean and we will update on the docs very soon to provide option for a custom RAK4630 without L10 (operating in Normal Voltage mode) to our customers. The module is available without L10 but this is a custom request and users must ensure that enough current will be provided to the Semtech transceiver chip. Using the built-in DCDC of nRF52 on Normal Voltage mode will not be enough during transmit. An external 3.3V is still needed.

**Comment by Nianmi** [comment]
So the RAK4630 can bo order from the store with no L10? I remember i have asked but got no response.

Yes if you remove the internal DC/DC converter you need to provide 3.3V. You need to provide 3.3V anyway. If the user provides the 3.3V the user is responsible to ensure the 3.3V are spect correctly, even in transmission mode. The point is often you don't have any Voltage higher than 3.3V. Or the next higher voltage is to high for the internal DC/DC converter.

I think there is some dokumentation missing that's what i try to fix whit this PR. In the schematic is clearly stated that L10 need do be removed. But nowhere is clarified where L10 is located. Yesterday i made an educated case and risked destroying my RAK4630 by removing L10. Some dokumentation would have been nice. Perhaps this dokumentation could be in the form of a topologic map?

**Comment by carlrakwireless** [comment]
It cannot be ordered from store since all standard modules have L10 connected. The note in the schematic is supposedly internal notes for RAK but of course it is open source so public can see it. If you need one, you can send request to inquiry@rakwireless.com.

**Comment by kneelyrac** [comment]
Hi @Nianmi 
Thank you for your contribution. 
I'll be closing this PR, and for further inquiries, you can refer to our [forum](https://forum.rakwireless.com/) and send the request to inquiry@rakwireless.com.

**Pull request closed without merging**
